service: serverless-test
frameworkVersion: "3"
useDotenv: true

provider:
  name: aws
  runtime: nodejs16.x
  stage: development
  region: ap-southeast-2
  timeout: 30
  environment:
    ALLOWS_INSECURE_SSL_CERTIFICATES: true
    OPENWEATHERMAP_API_KEY: ${env:OPEN_WEATHER_API_KEY}

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-add-api-key

functions:
  weatherApi:
    handler: src/handlers/weather.handler
    events:
      - http:
          path: weather
          method: get
          cors: true
          private: true

custom: 
  apiKeys:
    - myWeatherApiKey
